//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int request_id { get; set; }
        public Nullable<int> application_number { get; set; }
        public Nullable<System.DateTime> request_date { get; set; }
        public Nullable<int> equipment_id { get; set; }
        public Nullable<int> fault_type_id { get; set; }
        public string problem_description { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<int> worker_id { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual FaultTypes FaultTypes { get; set; }
        public virtual RequestStatus RequestStatus { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
